FROM golang:1.21 AS builder

WORKDIR /app

# Copy and build the Go app
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags '-s -w' -o webservice ./cmd/web

# Final Stage
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/webservice .

# Expose port and run the app
EXPOSE 8080
CMD ["./webservice"]